format = """
$username \
$directory \
$git_branch \
$git_status \
$git_state \
"""

[username]
show_always = true
style_user = "#eb6f92 bold"
format = '[$user ]($style)'
disabled = false

[directory]
style = "#9ccfd8 bold"
truncation_length = 1
truncation_symbol = '' 

[git_branch]
symbol = ' '
style = "bold #f6c177"
truncation_length = 4
truncation_symbol = ''
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_status]
style = "bold #ea9d34"